// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuUhCVsSft_EZQSGdDEPC6jy09l0qip4U',
    appId: '1:236625221748:web:9e984e8dd37116cb825921',
    messagingSenderId: '236625221748',
    projectId: 'fruit-hub-d58aa',
    authDomain: 'fruit-hub-d58aa.firebaseapp.com',
    storageBucket: 'fruit-hub-d58aa.firebasestorage.app',
    measurementId: 'G-L1909QG354',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBqHP4uHAEQe6myGkj5AqOd0km97do8c',
    appId: '1:236625221748:android:0b257467fcd2b497825921',
    messagingSenderId: '236625221748',
    projectId: 'fruit-hub-d58aa',
    storageBucket: 'fruit-hub-d58aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVvhlgdrFSDR7ZjZVjAL5PCtPUdoeslhI',
    appId: '1:236625221748:ios:d0dff01f6223d107825921',
    messagingSenderId: '236625221748',
    projectId: 'fruit-hub-d58aa',
    storageBucket: 'fruit-hub-d58aa.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
